global:
  # How frequently to scrape targets by default.
  scrape_interval: 10s
  # How long until a scrape request times out.
  scrape_timeout: 5s
  # How frequently to evaluate rules.
  evaluation_interval: 1m

# Alerting specifies settings related to the Alertmanager.
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
rule_files:
  - '/etc/prometheus/*.rules.yml'

# A list of scrape configurations.
scrape_configs:

  - job_name: prometheus
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    scheme: http
    static_configs:
    - targets: ['localhost:9090']
      labels:
        app: prometheus
        env: dev

  - job_name: alertmanager
    metrics_path: /metrics
    static_configs:
    - targets: ['alertmanager:9093']
      labels:
        app: alertmanager
        env: dev

  - job_name: cadvisor
    metrics_path: /metrics
    static_configs:
    - targets: ['cadvisor:8080']
      labels:
        app: cadvisor
        env: dev

  - job_name: node_exporter
    metrics_path: /metrics
    static_configs:
    - targets: ['node_exporter:9100']
      labels:
        app: node_exporter
        env: dev

  # https://docs.docker.com/config/daemon/prometheus/
  - job_name: docker_daemon
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9323']
        labels:
          app: docker
          env: dev